# set the base image 
FROM python:3.9.4

# File Author / Maintainer
MAINTAINER Emi/Ale

#add project files to the usr/src/app folder
ADD . /usr/src/app

#set directoty where CMD will execute 
WORKDIR /usr/src/app

#COPY . .

# Get pip to download and install requirements:
RUN pip install --no-cache-dir -r requirements.txt
RUN python manage.py migrate
RUN python manage.py collectstatic --noinput

# Expose ports
EXPOSE 8000

# default command to execute    
CMD exec gunicorn LanGuardian.wsgi:application --bind 0.0.0.0:8000 --workers 3