# Generated by Django 2.2.2 on 2021-07-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanGuardianSrv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='LanGuardianSrv'),
        ),
    ]
