# Generated by Django 2.2.10 on 2021-08-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('puerto', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('ide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LanGuardianCont.Dispositivo')),
            ],
        ),
    ]
