# Generated by Django 2.2.10 on 2021-10-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LanGuardianCont', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispositivo',
        ),
    ]
